export const UPDATE_VIEWPORT = 'UPDATE_VIEWPORT';
export const UPDATE_SELECTED_MENU = 'UPDATE_SELECTED_MENU';
export const UPDATE_AUTHENTICATION_STATE = 'UPDATE_AUTHENTICATION_STATE';
export const UPDATE_AUTHENTICATION_LOADING_STATE = 'UPDATE_AUTHENTICATION_LOADING_STATE';
